default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskManyo_development

test:
  <<: *default
  database: taskManyo_test

production:
  <<: *default
  database: taskManyo_production
  username: taskManyo
  password: <%= ENV['TASKMANYO_DATABASE_PASSWORD'] %>
